project:
  type: website

website:
  title: "Murali K | Engineer"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  comments:
    giscus:
      repo: iamurali/iamurali.github.com
format:
  html:
    theme:
      light: darkly
      dark: cosmo
    css: styles.css
    comments: false



