name: Check GH Pages Status

on:
  workflow_run:
    workflows: ["Pages Build and Deployment"]
    types:
      - completed

jobs:
  check-status:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail if Pages build failed
        run: |
          echo "GitHub Pages build failed!"
          exit 1
